### ISSUE TITLE
Error while running windows

### ISSUE THREAD

**Issue by abhilashsajeev** [zezo357/flutter_meedu_videoplayer#104]
While I was running the youtube example given in this repository following error happens @zezo357 

```
flutter: UnimplementedError: init() has not been implemented.
flutter: #0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28:21)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:404:25)
#3      MeeduPlayerController.setDataSource (package:flutter_meedu_videoplayer/src/controller.dart:462:37)
#4      _YoutubeExamplePageState._setDataSource 
```

**Comment by zezo357** [comment]
Did you write initmeeduplayer? Before your run app

**Comment by zezo357** [comment]
void main() { 
   initMeeduPlayer(); 
   runApp(const MyApp()); 
 }

**Comment by abhilashsajeev** [comment]
@zezo357 Yep. That solved it.  I was using from 4.0.11 Updated recently and it broke

Thank you very much @zezo357
