### ISSUE TITLE
Android emulator + virtualbox x86_64

### ISSUE THREAD

**Issue by amaxcz** [zezo357/flutter_meedu_videoplayer#146]
Using virtualbox (linux) flutter_meedu_videoplayer: ^4.2.13
Got emulator android-x86_64-7.1-r5.iso from https://www.fosshub.com/Android-x86-old.html

```
I/ExoPlayerImpl( 4274): Init 3067a64 [ExoPlayerLib/2.18.7] [x86_64, VirtualBox, innotek GmbH, 25]
D/NetworkSecurityConfig( 4274): No Network Security Config specified, using platform default
W/AudioCapabilities( 4274): Unsupported mime audio/ac3
W/AudioCapabilities( 4274): Unsupported mime audio/alac
W/AudioCapabilities( 4274): Unsupported mime audio/x-ape
W/AudioCapabilities( 4274): Unsupported mime audio/ffmpeg
W/AudioCapabilities( 4274): Unsupported mime audio/dts
W/AudioCapabilities( 4274): Unsupported mime audio/mpeg-L2
W/AudioCapabilities( 4274): Unsupported mime audio/vnd.rn-realaudio
W/AudioCapabilities( 4274): Unsupported mime audio/x-ms-wma
W/VideoCapabilities( 4274): Unsupported mime video/divx 
W/VideoCapabilities( 4274): Unsupported mime video/x-flv
W/VideoCapabilities( 4274): Unsupported mime video/vnd.rn-realvideo
W/VideoCapabilities( 4274): Unsupported mime video/vc1
W/VideoCapabilities( 4274): Unsupported mime video/ffmpeg
W/VideoCapabilities( 4274): Unsupported mime video/x-ms-wmv
I/VideoCapabilities( 4274): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 4274): MuxOMX ctor
I/MediaCodec( 4274): [OMX.ffmpeg.h264.decoder] setting surface generation to 4376577
E/ACodec  ( 4274): [OMX.ffmpeg.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
I/ACodec  ( 4274): codec does not support config priority (err -1010)
I/OMXClient( 4274): MuxOMX ctor
I/ACodec  ( 4274): codec does not support config priority (err -2147483648)
I/ACodec  ( 4274): codec does not support config operating rate (err -2147483648)
D/AudioTrack( 4274): Client defaulted notificationFrames to 6156 for frameCount 12312
D/MediaCodec( 4274): [OMX.ffmpeg.h264.decoder] setting dataspace on output surface to #104
D/SoftwareRenderer( 4274): setting dataspace on output surface to #104
```

**Comment by amaxcz** [comment]
also

```

I/ExoPlayerImpl( 3316): Release 9629843 [ExoPlayerLib/2.18.7] [x86_64, VirtualBox, innotek GmbH, 25] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
W/MessageQueue( 3316): Handler (android.os.Handler) {fc97423} sending message to a Handler on a dead thread
W/MessageQueue( 3316): java.lang.IllegalStateException: Handler (android.os.Handler) {fc97423} sending message to a Handler on a dead thread
W/MessageQueue( 3316):  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
W/MessageQueue( 3316):  at android.os.Handler.enqueueMessage(Handler.java:643)
W/MessageQueue( 3316):  at android.os.Handler.sendMessageAtTime(Handler.java:612)
W/MessageQueue( 3316):  at android.os.Handler.sendMessageDelayed(Handler.java:582)
W/MessageQueue( 3316):  at android.os.Handler.post(Handler.java:338)
W/MessageQueue( 3316):  at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.onLengthKnown(ProgressiveMediaPeriod.java:711)
W/MessageQueue( 3316):  at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.access$600(ProgressiveMediaPeriod.java:72)
W/MessageQueue( 3316):  at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1008)
W/MessageQueue( 3316):  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
W/MessageQueue( 3316):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/MessageQueue( 3316):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/MessageQueue( 3316):  at java.lang.Thread.run(Thread.java:761)
```

**Comment by zezo357** [comment]
If both media_kit and video_player fail 

I have nothing to do, I use them to play the videos so I can't edit them and errors posted doesn't help much sadly 😢
