### ISSUE TITLE
MacOS Exception: Error running pod install with ^4.2.6

### ISSUE THREAD

**Issue by aturiel** [zezo357/flutter_meedu_videoplayer#69]
Hi:

I configured the project as the readme.txt and I'm getting this error.

The MACOSX_DEPLOYMENT_TARGET is 11.0. 

Do you have any ideas?

```
Running pod install...                                           1,293ms
CocoaPods' output:
↳
  Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_meedu_videoplayer
      A media_kit_libs_macos_video
      A media_kit_native_event_loop
      A media_kit_video
      A screen_brightness_macos
      A screen_retriever
      A window_manager
      R video_player_macos
      - FlutterMacOS
      - device_info_plus
      - isar_flutter_libs
      - package_info_plus
      - path_provider_foundation
      - printing
      - shared_preferences_foundation
      - wakelock_macos

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `device_info_plus` from `Flutter/ephemeral/.symlinks/plugins/device_info_plus/macos`
    -> Fetching podspec for `flutter_meedu_videoplayer` from `Flutter/ephemeral/.symlinks/plugins/flutter_meedu_videoplayer/macos`
    -> Fetching podspec for `isar_flutter_libs` from `Flutter/ephemeral/.symlinks/plugins/isar_flutter_libs/macos`
    -> Fetching podspec for `media_kit_libs_macos_video` from `Flutter/ephemeral/.symlinks/plugins/media_kit_libs_macos_video/macos`
    make: Nothing to be done for `all'.
    -> Fetching podspec for `media_kit_native_event_loop` from `Flutter/ephemeral/.symlinks/plugins/media_kit_native_event_loop/macos`
    make: Nothing to be done for `all'.
    -> Fetching podspec for `media_kit_video` from `Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos`
    make: Nothing to be done for `all'.
    -> Fetching podspec for `package_info_plus` from `Flutter/ephemeral/.symlinks/plugins/package_info_plus/macos`
    -> Fetching podspec for `path_provider_foundation` from `Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/macos`
    -> Fetching podspec for `printing` from `Flutter/ephemeral/.symlinks/plugins/printing/macos`
    -> Fetching podspec for `screen_brightness_macos` from `Flutter/ephemeral/.symlinks/plugins/screen_brightness_macos/macos`
    -> Fetching podspec for `screen_retriever` from `Flutter/ephemeral/.symlinks/plugins/screen_retriever/macos`
    -> Fetching podspec for `shared_preferences_foundation` from `Flutter/ephemeral/.symlinks/plugins/shared_preferences_foundation/macos`
    -> Fetching podspec for `wakelock_macos` from `Flutter/ephemeral/.symlinks/plugins/wakelock_macos/macos`
    -> Fetching podspec for `window_manager` from `Flutter/ephemeral/.symlinks/plugins/window_manager/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "media_kit_native_event_loop":
      In Podfile:
        media_kit_native_event_loop (from `Flutter/ephemeral/.symlinks/plugins/media_kit_native_event_loop/macos`)

    Specs satisfying the `media_kit_native_event_loop (from `Flutter/ephemeral/.symlinks/plugins/media_kit_native_event_loop/macos`)` dependency
    were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-x64, locale en-ES)
    • Flutter version 3.7.11 on channel stable at /Users/alberto/Sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (4 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by zezo357** [comment]
Specs satisfying the `media_kit_native_event_loop (from `Flutter/ephemeral/.symlinks/plugins/media_kit_native_event_loop/macos`)` dependency
    were found, but they required a higher minimum deployment target.


This means its not set to the value recommend, did you change all to new value?

**Comment by aturiel** [comment]
Hi:

You're true I changed values of "MACOSX_DEPLOYMENT_TARGET" here:
- ```/macOS/Podfile```
- ```/macos/Runner.xcodeproj/project.pbxproj```

but forgot to set ```platform :osx, '11.0'``` on  ```/macOS/Podfile```

Many thanks

**Comment by zezo357** [comment]
Glad to know it was fixed
